//FICHIER DE CONFIGURATION//


#ifndef  DEF_CONFIG
#define DEF_CONFIG
//TRESOR//
    #define TRESOR 50

//PLATEAU//
    #define COTE 5

//PRODUCTION//
    #define COUT_OUVRIERE 1
    #define TEMPS_OUVRIERE 2
    #define COUT_REINE 20
    #define TEMPS_REINE 6
    #define COUT_SOLDAT 5
    #define TEMPS_SOLDAT 4

//TRANSFORMATION//
    #define COUT_TRANSFORMATION 30

//OUVRIERE IMMOBILE//
    #define RECOLTE_OUVRIERE 1

//COMBAT//
    #define FORCE_AGENT_VS_SOLDAT  25

#endif