# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/philippe/C_Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/philippe/C_Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/philippe/C_Project/CMakeFiles /home/philippe/C_Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/philippe/C_Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named C_Project

# Build rule for target.
C_Project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 C_Project
.PHONY : C_Project

# fast build rule for target.
C_Project/fast:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/build
.PHONY : C_Project/fast

affichage.o: affichage.c.o
.PHONY : affichage.o

# target to build an object file
affichage.c.o:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/affichage.c.o
.PHONY : affichage.c.o

affichage.i: affichage.c.i
.PHONY : affichage.i

# target to preprocess a source file
affichage.c.i:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/affichage.c.i
.PHONY : affichage.c.i

affichage.s: affichage.c.s
.PHONY : affichage.s

# target to generate assembly for a file
affichage.c.s:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/affichage.c.s
.PHONY : affichage.c.s

app.o: app.c.o
.PHONY : app.o

# target to build an object file
app.c.o:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/app.c.o
.PHONY : app.c.o

app.i: app.c.i
.PHONY : app.i

# target to preprocess a source file
app.c.i:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/app.c.i
.PHONY : app.c.i

app.s: app.c.s
.PHONY : app.s

# target to generate assembly for a file
app.c.s:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/app.c.s
.PHONY : app.c.s

combat.o: combat.c.o
.PHONY : combat.o

# target to build an object file
combat.c.o:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/combat.c.o
.PHONY : combat.c.o

combat.i: combat.c.i
.PHONY : combat.i

# target to preprocess a source file
combat.c.i:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/combat.c.i
.PHONY : combat.c.i

combat.s: combat.c.s
.PHONY : combat.s

# target to generate assembly for a file
combat.c.s:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/combat.c.s
.PHONY : combat.c.s

deplacement.o: deplacement.c.o
.PHONY : deplacement.o

# target to build an object file
deplacement.c.o:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/deplacement.c.o
.PHONY : deplacement.c.o

deplacement.i: deplacement.c.i
.PHONY : deplacement.i

# target to preprocess a source file
deplacement.c.i:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/deplacement.c.i
.PHONY : deplacement.c.i

deplacement.s: deplacement.c.s
.PHONY : deplacement.s

# target to generate assembly for a file
deplacement.c.s:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/deplacement.c.s
.PHONY : deplacement.c.s

fourmido_sdl.o: fourmido_sdl.c.o
.PHONY : fourmido_sdl.o

# target to build an object file
fourmido_sdl.c.o:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/fourmido_sdl.c.o
.PHONY : fourmido_sdl.c.o

fourmido_sdl.i: fourmido_sdl.c.i
.PHONY : fourmido_sdl.i

# target to preprocess a source file
fourmido_sdl.c.i:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/fourmido_sdl.c.i
.PHONY : fourmido_sdl.c.i

fourmido_sdl.s: fourmido_sdl.c.s
.PHONY : fourmido_sdl.s

# target to generate assembly for a file
fourmido_sdl.c.s:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/fourmido_sdl.c.s
.PHONY : fourmido_sdl.c.s

init.o: init.c.o
.PHONY : init.o

# target to build an object file
init.c.o:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/init.c.o
.PHONY : init.c.o

init.i: init.c.i
.PHONY : init.i

# target to preprocess a source file
init.c.i:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/init.c.i
.PHONY : init.c.i

init.s: init.c.s
.PHONY : init.s

# target to generate assembly for a file
init.c.s:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/init.c.s
.PHONY : init.c.s

instructions.o: instructions.c.o
.PHONY : instructions.o

# target to build an object file
instructions.c.o:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/instructions.c.o
.PHONY : instructions.c.o

instructions.i: instructions.c.i
.PHONY : instructions.i

# target to preprocess a source file
instructions.c.i:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/instructions.c.i
.PHONY : instructions.c.i

instructions.s: instructions.c.s
.PHONY : instructions.s

# target to generate assembly for a file
instructions.c.s:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/instructions.c.s
.PHONY : instructions.c.s

jeu.o: jeu.c.o
.PHONY : jeu.o

# target to build an object file
jeu.c.o:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/jeu.c.o
.PHONY : jeu.c.o

jeu.i: jeu.c.i
.PHONY : jeu.i

# target to preprocess a source file
jeu.c.i:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/jeu.c.i
.PHONY : jeu.c.i

jeu.s: jeu.c.s
.PHONY : jeu.s

# target to generate assembly for a file
jeu.c.s:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/jeu.c.s
.PHONY : jeu.c.s

plateau.o: plateau.c.o
.PHONY : plateau.o

# target to build an object file
plateau.c.o:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/plateau.c.o
.PHONY : plateau.c.o

plateau.i: plateau.c.i
.PHONY : plateau.i

# target to preprocess a source file
plateau.c.i:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/plateau.c.i
.PHONY : plateau.c.i

plateau.s: plateau.c.s
.PHONY : plateau.s

# target to generate assembly for a file
plateau.c.s:
	$(MAKE) -f CMakeFiles/C_Project.dir/build.make CMakeFiles/C_Project.dir/plateau.c.s
.PHONY : plateau.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... C_Project"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... affichage.o"
	@echo "... affichage.i"
	@echo "... affichage.s"
	@echo "... app.o"
	@echo "... app.i"
	@echo "... app.s"
	@echo "... combat.o"
	@echo "... combat.i"
	@echo "... combat.s"
	@echo "... deplacement.o"
	@echo "... deplacement.i"
	@echo "... deplacement.s"
	@echo "... fourmido_sdl.o"
	@echo "... fourmido_sdl.i"
	@echo "... fourmido_sdl.s"
	@echo "... init.o"
	@echo "... init.i"
	@echo "... init.s"
	@echo "... instructions.o"
	@echo "... instructions.i"
	@echo "... instructions.s"
	@echo "... jeu.o"
	@echo "... jeu.i"
	@echo "... jeu.s"
	@echo "... plateau.o"
	@echo "... plateau.i"
	@echo "... plateau.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

